# Generated by Django 3.2.9 on 2021-11-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211116_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='color',
        ),
    ]
